### ISSUE TITLE
最大勝点でソートした際の、最大勝点数が同一のチームの表示順

### ISSUE THREAD

**Issue by sawaken2021** [mokekuma-git/JLeague_Matches-Bar_Graph#55]
最大勝点でソートした際、同一の最大勝点のチームが複数ある場合の表示順が不定になっているようです。
※既に表示順位のPolicyが存在していたらごめんなさい

同一最大勝点数の場合は、①勝点数 ②得失点差 ③得点数 などのように通常の順位決定ルールによって決定するのはいかがでしょうか？

**Comment by mokekuma-git** [comment]
さっそくのご指摘、どうもありがとうございます。
ソート計算は、最新状態と過去の状態とで分けたりした結果、過去に一度バグを出したことがあります。
直したつもりになってましたが、取り切れていなかったかもしれません。

各チームごとに、
最新状態の勝ち点/最大勝ち点、得失点差、総得点数
表示時点での勝ち点/最大勝ち点、得失点差、総得点数
を計算しておいて、下記の関数で比較しています。

1.  team_sort_key「チーム並び順」で指定された勝ち点で比較
2. 得失点差で比較 (チーム並び順が最新状態か表示時点かで区別、以下同じ)
3. 総得点で比較
4. 前年の順位を元に比較

https://github.com/mokekuma-git/JLeague_Matches-Bar_Graph/blob/35ed3e8e1b186962099e6cd4dae051e49aa4dc66/docs/j_points.js#L361-L398

数字の計算ミスか、比較の間違いか、見直してみます。
上記すべての数字を出すと画面が煩いので、表示していませんでしたが、
チーム名のポップアップで負け試合表示するついでに出すようにしてみます。

**Comment by mokekuma-git** [comment]
(うっかり一度Closeしてしまいました)
まずは勝敗数や勝ち点、最大勝ち点、得点失点得失点差を、チーム名にフォーカスした時のポップアップに表示するようにしてみました。
これで、順位がおかしい時に、「計算した数字がおかしいか」「数字を比較する部分がおかしいか」が切り分けられるようになります。

#56 と同じで仕様が分かりにくかっただけかもしれませんが、まだおかしな表記が残っておりましたら、ご指摘くだされば幸いです。

**Comment by mokekuma-git** [comment]
勝ち点、得点などを見られるようにして、しばらく見てみましたが、意図しない順位は見つけられませんでした。
ただ、最大勝ち点で比較する時に、普通の勝ち点を無視するのは変な印象だったので、二番目の優先度で比較するように変更しました。
特に問題なさそうであれば、本件はこの修正でCloseとしたいと思います。

**Comment by mokekuma-git** [comment]
いったんCloseとします。おかしな順位付けが再現しましたら、再Openして対応します。
