### ISSUE TITLE
最大勝点ソートで、過去データ(2021/05/22あたり)を表示すると順位が正しく表示されない

### ISSUE THREAD

**Issue by sawaken2021** [mokekuma-git/JLeague_Matches-Bar_Graph#56]
- 今年の最大勝ち点
- 古い試合が下
- J1

の条件で5/22あたりを表示すると、順位が正しく表示されていません。

**Comment by mokekuma-git** [comment]
おそらく、仕様が分かりにくいのが問題なのかと思います。
「今年の最大勝ち点」「現在の勝ち点」を指定している時の順位ソートは、表示が過去に遡っているか否かに依存しません。
常に、その時点での最新の「最大勝ち点」「現在の勝ち点」で順位を決めています。
つまり、時間を遡ってもチームの順位が変わらない、という仕様にしています。

普通の、遡ったら表示時点での順位を見たい場合 (普通こちらが普通だと思います) 「表示時の最大勝ち点」「表示時の勝ち点」を選択してください。
こちらを選択肢の上位に入れ替えるようにします。

**Comment by sawaken2021** [comment]
なるほど、現時点での順位のまま過去の状況を見ることで、当時は勢いがあったor無かったってのがわかるということですね。確かにその観点で見れるのは良いですね。

期待したViewが、時間変更後、ソートを選択することで見られることを確認しました。迅速な対応ありがとうございます。
